### ISSUE TITLE
[Issue] Offline Charging broken with PE+ GSI 

### ISSUE THREAD

**Issue by Master37373** [Kethen/herolte_treble#1]
The lpm_installer.zip doesnt work with PE+ GSI. There is no Problem with non GSI version.
When Phone is off and I plug in the charger, the charging animation loads and shows the precentage for about 2-3 seconds. After that immediately the phone reboots back to the system. It seems it want to  function but than it conflicts with something. It is happening with wireless and cable charging.

**Comment by Kethen** [comment]
Noted
After showing percentage lpm should put the device into sleep mode, however it reboots instead when it is used with Andy Yan LineageOS based GSIs
I'll look more into it next weekend or the weekend after

**Comment by Kethen** [comment]
The issue stems from phh gsi restarting surfaceflinger even in charger mode, which then starts hwc, then triggers bootanimation to play
https://github.com/phhusson/device_phh_treble/blob/b67b41a7e4baf964dd88c618dfe508e7d76966a4/vndk.rc#L53

a workaround has been applied, please download lpm_installer.zip from the release and try again
