### ISSUE TITLE
[Issue] Encryption broken on PE+ GSI

### ISSUE THREAD

**Issue by Master37373** [Kethen/herolte_treble#2]
When i do Encryption the phone is stuck on a bootloop and will not boot into system. It is happening also with non gsi version, so it could be a rom issue which is device specific maybe

**Comment by Kethen** [comment]
Weird, do you know if it works on other phones with this GSI?

**Comment by Master37373** [comment]
No, idont know any other phones. I can only refer to my Galaxy S7 (SM-G930F, herolte)

**Comment by Kethen** [comment]
hmm, encryption seems to work with phh aosp and andy yan lineage os (need to manually reboot once when soft restart happens, after the android gear spinning encryption process), so this might be a rom specific issue

**Comment by Master37373** [comment]
Thats what i though, on lienage its working fine. Thank you so much
